### ISSUE TITLE
Making autocorrelation more efficient

### ISSUE THREAD

**Issue by doffen** [sevagh/pitch-detection#33]
Since the second half of a forward DFT's complex output vector contains the complex conjugates of the first half in reverse order, maybe the autocorrelation in MPM only needs to iterate over the first half of the two output vectors, thus reducing the number of complex multiplications?  
I propose changing these lines in acorr_r():
	for (int i = 0; i < N2; ++i)
		out[i] = outa[i] * std::conj(outb[i]) * scale;

to this (though I haven't tested it):
	for (int i = 0; i < N2/2; ++i) {
		out[i] = outa[i] * std::conj(outb[i]) * scale;
		out[N2-1 - i ] = std::conj(out[i]);
	}       

Are my assumptions correct?  I don't claim to be an FFT expert.  It's just a thought that occurred to me.

**Comment by sevagh** [comment]
I'll explore this with some benchmarks.

**Comment by sevagh** [comment]
```
for (int i = 0; i < N2/2; ++i) {
out[i] = outa[i] * std::conj(outb[i]) * scale;
out[N2-1 - i ] = std::conj(out[i]);
}
```
The second line there, `out[N2-1 - i] = std::conj(out[i]);` is causing the results to be junk. However, you are onto something. Since at the bottom of MPM, I only take the first N results of the FFT:

```
	std::vector<double> normalized_result(N, 0.0);
	for (int i = 0; i < N; ++i)
		normalized_result[i] =
		    std::real(result[i + (N2 - N)]) / std::real(result[N2 - N]);
```
I follow your suggestion to cut the `conj * scale` loop in half:
```
	std::complex<float> scale = {1.0f / (float)N2, 0.0};
	for (int i = 0; i < N; ++i) 
		out[i] = outa[i] * std::conj(outb[i]) * scale;
```
This gives the identical detected pitch outputs with better performance (quite obvious the reason why).

**Comment by sevagh** [comment]
https://github.com/sevagh/pitch-detection/commit/477b09560955422991a0ebe09fc6c2deb61740ea
